### ISSUE TITLE
Set indices format on monthly basis?

### ISSUE THREAD

**Issue by riupie** [fluent/fluentd-kubernetes-daemonset#1322]
I have fluentd deployment on kubernetes using following config:

```
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: cri
          - name: FLUENTD_PROMETHEUS_CONF
            value: disable
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: FLUENT_CONTAINER_TAIL_PARSER_TIME_FORMAT
            value: "%Y-%m-%dT%H:%M:%S.%N%:z"
          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
            value: "/var/log/containers/fluent*"
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
            value: k8s-staging
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
            value: k8s-staging
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
```
Using above config, it will generate indices on daily basis like below:
```
k8s-staging-2021.11.10
k8s-staging-2021.11.12
k8s-staging-2021.11.13
...
```
How to set my indices set on monthly basis?

**Comment by fujimotos** [comment]
You just need to specify your own format to `index_name`, instead
of relying on `logstash_format`.

Replace the following section:

```yaml
 - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
   value: k8s-staging
 - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
   value: k8s-staging
```

with this:

```yaml
 - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
   value: false
 - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
   value: "k8s-staging-%Y.%m"
```
