### ISSUE TITLE
FluentD not sending application logs to open telemetry collector

### ISSUE THREAD

**Issue by saritatewari4** [fluent/fluentd-kubernetes-daemonset#1423]
Hello, I am trying to send all application logs of each pods to open telemetry collector . What configuration  I have to use for that.

Currently I am using this:
`   <match *.*>
      @type forward
      <server>
        host <OTEL_HOST>
        port <OTEL_PORT>
      </server>
    </match>`

This configuration is forwarding fluentD pods logs to open telemetry, but I need to send application logs running on EKS, which are  forwarded  to cloud watch too.

I am using fluentd-kubernetes-daemonset:v1.7.3-debian-cloudwatch-1.0 this image currently.

**Comment by Hronom** [comment]
@saritatewari4 for me this works:

Stock config from here https://artifacthub.io/packages/helm/fluent/fluentd

Modified `04_outputs.conf` section:
```
      <label @OUTPUT>
        <match **>
          @type forward
          send_timeout 60s
          recover_wait 10s
          hard_timeout 60s
    
          <server>
            name opentelemetry-collector
            host opentelemetry-collector.opentelemetry.svc.cluster.local
            port 8006
            weight 100
          </server>
        </match>
      </label>
```

Then using helm chart `opentelemetry-collector` https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector

I put this in `values.yaml`:
```
  ports:
    fluentforward:
      enabled: true
      containerPort: 8006
      servicePort: 8006
      hostPort: 8006
      protocol: TCP
```
and
```
  config:
    receivers:
      jaeger: null
      fluentforward:
        endpoint: ${env:MY_POD_IP}:8006
```

Hope it get you some inspiration
