### ISSUE TITLE
Make the fluentd conf configurable from configMap

### ISSUE THREAD

**Issue by vidhy** [fluent/fluentd-kubernetes-daemonset#174]
We can have the config files retrieved from configMap ,Instead of baking the fluentd conf files inside the docker image. This would eneble user to give custom configurations.

**Comment by vpistis** [comment]
In my installation I replace config files using a config map mounted into the fluent config path like so:

```
volumeMounts:
  - name: config-volume
    mountPath: /fluentd/etc
```
and for the volume:
```
volumes:
  - name: config-volume
    configMap:
      name: fluentd-config
```
