### ISSUE TITLE
where do I set FLUENT_UID to 0?

### ISSUE THREAD

**Issue by sdanieru** [fluent/fluentd-kubernetes-daemonset#188]
hi y'all, can anyone elucidate on the instructions: `set FLUENT_UID environment variable to 0 in your kubernetes configuration`, as mentioned in the project Readme?
My first inclination is to define this env var in, for example, the  `fluentd-daemonset-elasticsearch.yaml` file along with the other `containers.env` declarations but the fact that it's not already there suggests this is supposed to be defined somewhere else? How/where should this be defined?
Any help appreciated!

**Comment by MathieuMailhos** [comment]
Yes, simply put it in your daemonset with other environment variables. That works for me:

```
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.mydomain.com"
          - name: FLUENT_UID
            value: "0"
```
