### ISSUE TITLE
Help in building a new image with fluentd.conf file change

### ISSUE THREAD

**Issue by lp060** [fluent/fluentd-kubernetes-daemonset#196]
Hi,

Can anyone please help me with the procedure to build a new image if I make some code changes to fluentd.conf to pass new config params? I have modified fluentd plugin for kinesis to pass new config params. Need to build a new image with the changed plugin code.

**Comment by hobbsh** [comment]
You can just use a configmap to override the config that ships with this image - no need to build your own

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd
    version: v1
    kubernetes.io/cluster-service: "true"
data:
  fluent.conf: |-
    YOUR RAW CONFIG
```

Then mount it in the same place the image expects it, which is `/fluentd/etc/`

```
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc/
          readOnly: false
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          defaultMode: 0666
          name: fluentd-config
```
