### ISSUE TITLE
Fluentd not pushing the logs to the AWS Elastic Search Service.

### ISSUE THREAD

**Issue by ravvereddy** [fluent/fluentd-kubernetes-daemonset#199]
Hi,

I have a kubernetes cluster and I am trying to push the kubernetes logs to aws elastic search service.

Here is the link i am following and i could not able to push the logs to AWS Elastic Search.
https://github.com/heptio/fluentd-yaml

ubuntu@ip-172-31-12-81:~/test/fluentd-yaml$ kubectl logs  fluentd-kz4hp  --namespace=delete
2018-09-21 13:24:20 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2018-09-21 13:24:20 +0000 [info]: starting fluentd-0.12.32
2018-09-21 13:24:21 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.2'
2018-09-21 13:24:21 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.26.2'
2018-09-21 13:24:21 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.8.3'
2018-09-21 13:24:21 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.3'
2018-09-21 13:24:21 +0000 [info]: gem 'fluentd' version '0.12.32'
2018-09-21 13:24:21 +0000 [info]: adding match pattern="fluent.**" type="null"
2018-09-21 13:24:21 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2018-09-21 13:24:21 +0000 [info]: adding match pattern="es.**" type="aws-elasticsearch-service"
2018-09-21 13:24:21 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error="Unknown output plugin 'aws-elasticsearch-service'. Run 'gem search -rd fluent-plugin' to find plugins"
2018-09-21 13:24:21 +0000 [info]: process finished code=256
2018-09-21 13:24:21 +0000 [warn]: process died within 1 second. exit.

Here is the file I am using 
fluentd-1.6.yaml
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: delete
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" }]
    spec:
      serviceAccountName: fluentd-service-account
      containers:
      - name: fluentd
        image: quay.io/fluent/fluentd-kubernetes-daemonset
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "https://search-fluentd-elasticsearch-mhksn7zojhmro732426eu7sk3a.ap-south-1.es.amazonaws.com"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "443"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentdconf
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentdconf
        configMap:
          name: fluentd-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  namespace: delete
data:
  fluent.conf: |-
    @include kubernetes.conf
    <match es.**>
       type "aws-elasticsearch-service"
       log_level info
       include_tag_key true
       host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
       port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 5s
       max_retry_wait 30
       disable_retry_limit
       num_threads 8

       ### AWS ElasticSearch needs this set to false.  See
       ### https://discuss.elastic.co/t/elasitcsearch-ruby-raises-cannot-get-new-connection-from-pool-error/36252/10
       reload_connections false
    </match>


---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: fluentd-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-service-account
subjects:
- kind: ServiceAccount
  name: fluentd-service-account
  namespace: delete

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: fluentd-service-account
  namespace: delete
rules:
  - apiGroups: ["*"]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - watch
      - list

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-service-account
  namespace: delete
```

can any one help me how to push the logs from my kubernetes cluster to AWS Elastic Search.

Thanks in Advance.
