### ISSUE TITLE
Overwriting kubernetes.conf

### ISSUE THREAD

**Issue by kurktchiev** [fluent/fluentd-kubernetes-daemonset#209]
So maybe I am going crazy but no matter what I seemingly cannot overwrite the kubernetes.conf you guys have in the image with my own. I am trying to pass in my own configMap and mount it directly over the kubernetes.conf you guys provide. I keep failing spectacularly with: 
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/74266a12-d16f-11e8-bcee-a4bf01144874/volumes/kubernetes.io~configmap/diamanti-fluentd-config\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/bd5eff3dbef6a63c468912c06c74836e80fd9a389fb4fd20ac4fe5d04f270733/rootfs\\\" at \\\"/var/lib/docker/devicemapper/mnt/bd5eff3dbef6a63c468912c06c74836e80fd9a389fb4fd20ac4fe5d04f270733/rootfs/fluentd/etc/kubernetes.conf\\\" caused \\\"not a directory\\\"\""

I am trying to do this as such:

```
volumeMounts:
    - name: diamanti-fluentd-config
         mountPath: /fluentd/etc/kubernetes.conf
         subPath: kubernetes.conf
```
