### ISSUE TITLE
Allow ssl_version passthrough via DaemonSet ENV to fluent.conf

### ISSUE THREAD

**Issue by johnnason** [fluent/fluentd-kubernetes-daemonset#238]
Right now using fluent-plugin-elasticsearch at v2.11.0, you get a TLS_v1 default for `ssl_version`.

_Pretty_ outdated version at this point (I needed to jump through some hoops to allow it).

Ideally, `FLUENT_ELASTICSEARCH_SSL_VERSION` would be a pass-through to set the ssl_version of fluent.conf via the ENV definition in the DaemonSet, e.g. 
```
    spec:
      containers:
      - env:
        - name: FLUENT_ELASTICSEARCH_SSL_VERSION
          value: TLSv1_2
```
