### ISSUE TITLE
CrashLoopBackOff with "No such file or directory"

### ISSUE THREAD

**Issue by mleneveut** [fluent/fluentd-kubernetes-daemonset#246]
I want to deploy a fluentd deamonset in my Azure AKS (kubernetes 1.11.5) to send logs to Elastcisearch.

I tried debian-elasticsearch 1.3 and 0.12 but I got a CrashLoopBackOff without any log.

My conf : 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluentd/fluentd-kubernetes-daemonset:elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-discovery"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_UID
            value: "0"
          - name:  FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
            value: "fluentd"
          - name: FLUENT_ELASTICSEARCH_USER
            value: none
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: none
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-source
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-source
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

with a configmap : 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |-
    @include systemd.conf
    @include kubernetes.conf
    <system>
      log_level debug
    </system>
    <match **>
      @type elasticsearch
      @id out_es
      @log_level debug
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      path "#{ENV['FLUENT_ELASTICSEARCH_PATH']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'true'}"
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'fluentd'}"
      logstash_format true
      index_name fluentd
      type_name fluentd
      <buffer>
        flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
        flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
        chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
        queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
        retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
        retry_forever true
      </buffer>
    </match>

    <filter kubernetes.**>
      @type parser
      format multiline_grok
      key_name message
      <grok>
        pattern \{%{TIMESTAMP_ISO8601:time}\} \[%{DATA:logLevel}\] \[%{DATA:code}\] %{DATA:caller} &\$ %{DATA:logMessageType} &\$ %{DATA:message} &\$ %{DATA:correlationId} &\$ %{DATA:userId} &\$ %{DATA:data} &\$ %{DATA:operation} &\$ %{DATA:error} &\$ (?<stackTrace>.*)
      </grok>
      multiline_start_regexp /^{/
    </filter>
```

I set the log_level to debug but I still don't have any log in the fluentd pods, only : 

```
$ kubectl logs -n monitoring fluentd-fw89p
: No such file or directory
```

The describe doesn't say much : 

```
Events:
  Type     Reason   Age                From                               Message
  ----     ------   ----               ----                               -------
  Normal   Pulled   12s (x3 over 31s)  kubelet, aks-nodepool1  Container image already present on machine
  Normal   Created  11s (x3 over 30s)  kubelet, aks-nodepool1  Created container
  Normal   Started  11s (x3 over 30s)  kubelet, aks-nodepool1  Started container
  Warning  BackOff  10s (x3 over 28s)  kubelet, aks-nodepool1  Back-off restarting failed container
```

Do you have any idea how to debug this ?

Thanks.

**Comment by shinebayar-g** [comment]
@mleneveut I think you're trying to mount config file over wrong directory.

```yaml
        volumeMounts:
        - name: config-source
          mountPath: /fluentd/etc
```
I think it should should be
```yaml
        volumeMounts:
        - name: config-source
          mountPath: /fluentd/etc/
```

Also your configMap contains only `fluent.conf`. So even if you mount this configmap over `/fluentd/etc` directory. This directory will only have `fluent.conf` file. Existing files will be shadowed.

So 
```yaml
data:
  fluent.conf: |-
    @include systemd.conf            # This will not work, since systemd.conf is not there
    @include kubernetes.conf        # This will not work, since kubernetes.conf is not there
```
