### ISSUE TITLE
Update daemonset to apps/v1 api version

### ISSUE THREAD

**Issue by alexbrand** [fluent/fluentd-kubernetes-daemonset#249]
The `extensions/v1beta1` API version has been deprecated since kubernetes 1.8 (https://github.com/kubernetes/kubernetes/pull/51828). 

Update the fluentd DaemonSets to `apiVersion: apps/v1`.

**Comment by repeatedly** [comment]
Only replace `extensions/v1beta1` with `apps/v1` is enough?
No need other changes, right?

**Comment by AndrewX192** [comment]
It is also necessary to set the selector and template metadata

`missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec`

e.g.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-stackdriver
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      name: fluentd-stackdriver
  template:
    metadata:
      labels:
        name: fluentd-stackdriver
        k8s-app: fluentd-logging
        version: v1
    spec:
    ...
```
