### ISSUE TITLE
multiline message (like ruby exception) is divided into single line messages.

### ISSUE THREAD

**Issue by zerthimon** [fluent/fluentd-kubernetes-daemonset#266]
I'm seeing that a ruby exception comes in form of separate messages for each line. Does it work as intended ?

**Comment by repeatedly** [comment]
It is docker limitation. Docker generates json logs per line.
See also: https://docs.fluentd.org/v0.12/articles/docker-logging#additional-step-2:-concatenate-multiple-lines-log-messages

**Comment by zerthimon** [comment]
@repeatedly What do I have to do to get this concat snippet into the fluentd config template ? Is there an option to configure this via a configMap? Or is there another way around ?

**Comment by bdashrad** [comment]
@zerthimon since `@include conf.d/*` was added [here](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/templates/conf/fluent.conf.erb#L10) you can add your own configmap and a volume to the daemonset yaml:

configmap:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: YOUR-CONFIG-MAP
data:
  00_docker_concat.conf: |-
    <filter docker.**>
      @type concat
      key log
      stream_identity_key container_id
      multiline_start_regexp /^-e:2:in `\/'/
      multiline_end_regexp /^-e:4:in/
    </filter>
```

Excerpt of what you need to add to daemonset:
```yaml
spec:
  template:
    spec:
      containers:
          volumeMounts:
            - name: kubesconf
              mountPath: /fluentd/etc/conf.d
      volumes:
      - name: kubesconf
        configMap:
          name: YOUR-CONFIG-MAP
```

Be aware that the example filter block is for fluentd v0.12 and would need to be changed for v1.x
