### ISSUE TITLE
cloudwatch: not using service linked roles in EKS

### ISSUE THREAD

**Issue by maust** [fluent/fluentd-kubernetes-daemonset#373]
When running fluent/fluentd-kubernetes-daemonset:v1.7.3-debian-cloudwatch-1.0 with a service linked role:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::811293737904:role/....
```
Fluentd should use the service linked role for authenticating with AWS, instead of using a IAM role attached to the node.

Details see: https://docs.aws.amazon.com/eks/latest/userguide/using-service-linked-roles.html

But from the logs it looks like it still trys to use the node IAM role instead:
```
2019-11-22 06:19:19 +0000 [warn]: #0 [out_cloudwatch_logs_systemd] failed to flush the buffer. retry_time=12 next_retry_seconds=2019-11-22 06:56:13 +0000 chunk="597e8e5eff7878bf0c81b05b1006da7c" error_class=Aws::CloudWatchLogs::Errors::AccessDeniedException error="User: arn:aws:sts::AWS_ACCOUNT:assumed-role/IAM_NODE_ROLE/i-0b423cfb59c5e2783 is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:eu-central-1:AWS_ACCOUNT:log-group::log-stream:"
```

AWS SDK introduced support for service linked roles, e.g. in the Ruby SDK with 2.11.345 - see https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

I am not exprienced with ruby and I find it hard to find out which version of aws sdk is actually used. In https://github.com/fluent/fluentd-kubernetes-daemonset/blame/master/docker-image/v1.7/debian-cloudwatch/Gemfile it states `gem "aws-sdk-cloudwatchlogs", "~> 1.0"`

So which version is actually bundled? If it is an older version, could we upgrade?

Thanks a lot!
