### ISSUE TITLE
The log cannot readable 

### ISSUE THREAD

**Issue by bjlvfei** [fluent/fluentd-kubernetes-daemonset#405]
Hi Team,

it's seems that the fluent can not read the containner log. Did you have any idea?

/var/log/containers/air412-worker-2_air412_airflow-worker-adc180a2ec3ce2ff916bc954a6196cc059320c36381f33ba1641a464e1a70906.log unreadable. It is excluded and would be examined next time.

I check the container inside as below. 
root@fluentd-krrhv:/home/fluent# ls -lrt /var/log/containers/air412-worker-6_air412_airflow-worker-7f69437e5fa29211e254e6008de9feb61864588810cb43e90c0a209cbe1332ed.log
lrwxrwxrwx 1 root root 94 Feb 12 04:13 /var/log/containers/air412-worker-6_air412_airflow-worker-7f69437e5fa29211e254e6008de9feb61864588810cb43e90c0a209cbe1332ed.log -> /var/log/pods/air412_air412-worker-6_e5256708-ce75-4f26-92ae-cb064e29e343/airflow-worker/0.log

There also no this directory. 
root@fluentd-krrhv:/home/fluent# cd /var/log/pods
bash: cd: /var/log/pods: No such file or directory

DaemonSet yaml file as below.
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      # Enable tolerations if you want to run daemonset on master nodes.
      # Recommended to disable on managed k8s.
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-graylog
        imagePullPolicy: IfNotPresent
        env:
          - name:  FLUENT_GRAYLOG_HOST
            value: "graylog-1.graylog.graylog.svc.cluster.local"
          - name:  FLUENT_GRAYLOG_PORT
            value: "12201"
          - name: FLUENT_UID
            value: "0"
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            # ===========
            # Less memory leads to child process problems.
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/log/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/log/containers
```

Levi
Thanks
