### ISSUE TITLE
rpc error: code = 2 desc = "oci runtime error: write parent: broken pipe"

### ISSUE THREAD

**Issue by alterx** [fluent/fluentd-kubernetes-daemonset#42]
Hey guys, 

I'm trying to deploy this daemonset (the cloudwatch version) to a kubernetes cluster.
First I tried with a cluster I have in AWS (Kube v 1.5.x) but it didn't work. I thought it was an issue with the version so now I've installed minikube (Kube v 1.6.4) but I keep getting the same error:

```
Failed to start container with id 4fe035a153fa874b6d6fc48e798ca4148d1675d6c54f04344bfb7cbbe48cba72 with error: rpc error: code = 2 desc = failed to start container "4fe035a153fa874b6d6fc48e798ca4148d1675d6c54f04344bfb7cbbe48cba72": Error response from daemon: rpc error: code = 2 desc = "oci runtime error: write parent: broken pipe"
```
My .yaml file looks like this:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: fluentd-cloudwatch
  name: prod-fluentd-cloudwatch
spec:
  selector:
    matchLabels:
      app: fluentd-cloudwatch
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fluentd-cloudwatch
    spec:
      containers:
      - env:
        - name: AWS_REGION
          value: us-east-1
        - name: LOG_GROUP_NAME
          value: NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: secret-fluentd-cloudwatch
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: secret-fluentd-cloudwatch
        image: fluent/fluentd-kubernetes-daemonset:v0.12-debian-cloudwatch
        imagePullPolicy: IfNotPresent
        name: prod-fluentd-cloudwatch
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
---
apiVersion: v1
data:
  aws_access_key_id: 'ACCESS_KEY'
  aws_secret_access_key: 'SECRET'
kind: Secret
metadata:
  labels:
    app: fluentd-cloudwatch
  name: secret-fluentd-cloudwatch
type: Opaque
```
I've done a ton of research and posted my question in several Slack groups but still no luck, has anyone stumbled upon this issue? I'm not sure if it's a bug or just something I'm missing.

Thanks in advance
