### ISSUE TITLE
Fluentd installation instructions for AWS Elasticsearch Service

### ISSUE THREAD

**Issue by melissajenner22** [fluent/fluentd-kubernetes-daemonset#488]
We use AWS Elasticsearch Service. We would like to install fluentd to our Kubernetes cluster. Fluentd sends logs to AWS Elasticsearch Service. Is there any instructions of how to do it? At this link, https://docs.fluentd.org/v/0.12/articles/kubernetes-fluentd, it shows steps on sending the logs to an Elasticsearch Pod. It means the elasticsearch is installed inside Kubernetes cluster.      

The link above shows make changes in fluentd-daemonset-elasticsearch.yaml (see below) for elasticsearch pod. What configuration changes I need to make for AWS elasticsearch service?
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  ...
spec:
    ...
    spec:
      containers:
      - name: fluentd
        image: quay.io/fluent/fluentd-kubernetes-daemonset
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-logging"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
            ......
```
