### ISSUE TITLE
Random missing log hours in S3 bucket

### ISSUE THREAD

**Issue by fvasco** [fluent/fluentd-kubernetes-daemonset#504]
I detected an issue on Fluentd on S3, I looked for it but I cannot find anything useful.

I found some missing log blocks in a container, from its start to 10:00, from 13:00 to 14:00, from 15:00 to 19:00, from 20:00 to 22:00, from 23:00 to midnight.
Nothing was restarted, we send some SIGHUP signals to force log flush on specific events.

We are using a plain configuration:

```yaml

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      kubernetes.io/cluster-service: 'true'
      name: fluentd
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubernetes.io/cluster-service: 'true'
        name: fluentd
      annotations:
        iam.amazonaws.com/role: fluentd
    spec:
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: ''
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: ''
      containers:
        - name: fluentd
          image: 'fluent/fluentd-kubernetes-daemonset:v1.11-debian-s3-1'
          env:
            - name: S3_BUCKET_REGION
              value: us-east-1
            - name: S3_BUCKET_NAME
              value: ...
            - name: FLUENTD_PROMETHEUS_CONF
              value: disable
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: node
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
```

Fluentd log attached.
[fluentd-vfp5x.log.gz](https://github.com/fluent/fluentd-kubernetes-daemonset/files/5428187/fluentd-vfp5x.log.gz)

This is the expected behavior?
How I can configure Fluentd to send all logs to S3?
