### ISSUE TITLE
Provide example Prometheus configuration for scraping the exposed Fluentd metrics

### ISSUE THREAD

**Issue by romankolpak** [fluent/fluentd-kubernetes-daemonset#540]
Hi,

I'm having trouble finding a way to configure Prometheus to scrape the metrics, exposure of which is configured in the `prometheus.conf` file. The docs of the plugin this deamonset is using (https://github.com/fluent/fluent-plugin-prometheus) don't seem to help either -- their example is using both Fluentd and Prometheus deployed on the `localhost`, which is pretty trivial to configure for. This deamonset is using a more complicated setup of having several Fluentd pods, all exposing their metrics on localhost:24321, and there doesn't seem to be a good example of Prometheus configuration for this setup anywhere I looked.

Any tips on how to configure Prometheus to scrape all metrics exposed on every Fluentd pod's localhost:24321 in the DeamonSet? Any chance we could get a configuration example for this case?

**Comment by andrew-pickin-epi** [comment]
This is actually a general Prometheus question not a fluentd daemonset. 

It rather depends on how you are deploying and configuring prometheus.
For example are you using the helm chart at https://github.com/prometheus-community/helm-charts?

So prometheus k8s deployments come with the notion of `ServiceMonitor`. See [here](https://observability.thomasriley.co.uk/prometheus/configuring-prometheus/using-service-monitors/)
Basically you register your metrics endpoint as a monitored service and prometheus scans for them and connects. 
You don't need to point prometheus at individual pods - that wouldn't survive a pod being replaced.

For the record here is my Service/ServiceMonitor config:
```
apiVersion: v1
kind: Service
metadata:
  name: fluentd-metrics
  namespace: logging
  labels:
    k8s-app: fluentd
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd
  ports:
    - name: prometheus
      port: 24231
      targetPort: 24231
```

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluentd-metrics
  namespace: logging
spec:
  selector:
    matchLabels:
      k8s-app: fluentd
  endpoints:
  - port: prometheus
    path: /metrics
```
