### ISSUE TITLE
Fluentd DaemonSet not sending events to Elasticsearch 7.x when FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT is false

### ISSUE THREAD

**Issue by cotjoey** [fluent/fluentd-kubernetes-daemonset#550]
I have been trying to figure out for over a week why my events are not being sent to Elasticsearch when I used the environment variable "FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT" with value "false".

 I need to set that env to false because I need a custom index name for the ILM to work. Those are my environment variables.:

```
env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-remote"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "https"
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          - name: FLUENT_ELASTICSEARCH_USER
            value: "logstash"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "XXXXX"
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT
            value: "false"
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME
            value: "logstash"
          - name: FLUENT_ELASTICSEARCH_INCLUDE_TIMESTAMP
            value: "true"
```

I am using image: `fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch`

I really don't know what I am doing wrong at this point whereas when the value is true, it ships the logs, when the value is false, it doesn't.

Thank you for any help you can provide.

**Comment by cotjoey** [comment]
I resolved this issue by using the additional following three environment variables to my fluentd yaml file:

```
env:
         - name: FLUENT_ELASTICSEARCH_ENABLE_ILM
           value: "true"
          - name: FLUENT_ELASTICSEARCH_TEMPLATE_FILE
            value: /host/index_template.json
          - name: FLUENT_ELASTICSEARCH_TEMPLATE_NAME
            value: "logstash-fluentd-kubernetes"
```

```
volumeMounts:
        - name: es-template
          mountPath: /host
          readOnly: true
```

```
volumes:
- name: es-template
        configMap:
          name: es-template
```

ConfigMap
```
---
apiVersion: v1
data:
  index_template.json: |-
    {
        "index_patterns": [
            "logstash-fluentd-kubernetes-*"
        ]
    }
kind: ConfigMap
metadata:
  name: es-template
  namespace: kube-system
```

After doing that, my index started showing in Kibana.
