### ISSUE TITLE
Reduce fluentd container logging output

### ISSUE THREAD

**Issue by annymsMthd** [fluent/fluentd-kubernetes-daemonset#83]
Currently the fluentd container is outputting info to stdout. There should be a way to increase the logging to warn or error as maybe an Environment variable for the container. This will reduce noise in production environments.

**Comment by StratusChris** [comment]
Looks like you can do this with an environment variable on the container. The entrypoint.sh pulls command line options from the FLUENTD_OPT variable.

Example container spec with FLUENTD_OPT setting to warn (-q is warn, -qq is error):
```
containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.3.3-debian-cloudwatch-1.1
        env:
          - name: LOG_GROUP_NAME
            value: "kubernetes"
          - name: AWS_REGION
            value: "us-east-1"
          - name: FLUENT_UID
            value: '0'
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
          - name: FLUENTD_OPT
            value: "-q"
```
